---
services:
  sub-store:
    build: 
      context: sub-store
      args:
        # 改成你自己的
        URL: https://sub.example.com/xxxxxxxx
    container_name: sub-store
    hostname: sub-store
    # environment:
    #   # 一般不需要动
    #   - SUB_STORE_BACKEND_SYNC_CRON=55 23 * * *
    ports:
      - 39080:80
    volumes:
      - ./db:/db
    restart: unless-stopped